---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgBaq9ud458jrTq6YVkHf2b6fzMA/2VZY0lo157G3yKF1/qbFQNX7MzK+8q6aeBzbi8/NEfXLmQHXZE+Rx3OvCLU3zgmsMToZobd4x3dSUFaruVNSVNHJ4rfRvoCK8Uk4qAAJNGHUZNILf9xHFQvAeB4tzulTkMGIJNAhr5NPGyoZnq4ulcao33i6PDnQieqic42wP1W1aTXfGy/ze8XSKF8ozZ+xMxo9Gvd+8lYzS0cYPJDh+5UAow/ns+9/Myl4KLmAgo0W2Wb3s5U8WEaP6LY0clr5V5W7sr3PkNRgZ/YJDYV8pXqxDvmYUqFDISbVFE9b9IKi/UemsfSVcCwJFOHzAbimVsLV/uNImO/Y5oUTshRvDLKeYjX40tu+o7gez+EBq55iGMSweFgtdX7hNvjRH4Mk/x9Gi3UX+tjxQUZQyDovX5ZCkcxKZkvSW9U5a+buSMW0HW60dEE4qEO/2JAT7vgVdZ1GvDkenO2hsDrpCe5OWy6SFA7H5bFgKFksjBtBYIgzK784HEf2+fOXOcW55jfpzbH5m88QfWrOGkGll5Ko4Eb0CdFaZbFpvdmKOcW9CHbPjWSCA8fu2OU+mWYeEgV+1PeM+MCww0ok4bvxvfHn8wlwgSN7Xj1zHx+Ac2xqPrM6tiAMCOv/pbYtBsHASbACoUmYpL2OUEmSdg6YmVgzQ9TQ483Xus69Y+EEaQP6Z0ZqFxR5MhZ7a0CUhm2QNJmbSU=
    username: AgCzsCxAZFhgEU5CSwKHXmJ+TscdE8PlT9kwYvnlFPhqYf4dQEjMK7D2HGIZQ9400xZmzAkkQkiTsInt8Tal9MnKwRvY4M/Hc+B/4t1RUxiOoaFXpGQa1r3LLpaLulL9eFC0NcM/81nXqzGfI71t7E31CyKhq5KOjw0713SfXtLwfomlmWiZMTjpb5l7mhJwshkrBkxA1e5VgQssz7JSshye1J2wfnTQiy5mEmfzTn9Hy4N0JB3aQ5gRYM94q5Wzty61oJ/CLNBAUC7gsDO3sgR3O8jKTPlJrh43Z9k56tISe6PdAqY3nv87oIGGn6WQyUCUtzx49hFIWuDKj9bu3XPAuYDKWeBejMd/faNkTylOdhkcTHvRa7VDTDBygLgT9S9fRmugPxyyncIlHrV5SPJeocmhD1IEj4CwmsKsfEfaq5GUqmuBiYkN69WcdZriD+CoUxjcR8HQLRGwB6XDWWjLq6OhgwbSFgjBi0pDoVaMwZf9zVg/zndOLXzQkeCXITs7FgNjxciMewvY2ROIGW0XNQoLNQB/Sk+R4VsLLIwjuCCVIyMmabiyVdtBbd/IbbhD8EaiLQ0VRGp6qA9KEQtNeyfy399tjvpbt9WgT3YvxZh7NZ7sx+ZizIanYgQiZRQaGOlyS0g8tbfllSh/5xVsEpskjQOPS3BbT9zRcLAyI46QnR3+A497Z2x7iqsLrKIbCbDf4VZ2z/TcwAE=
  template:
    metadata:
      name: db-credentials
      namespace: prod
