---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgAY8qSRI7ZZTBRcijjk03ZaVXuTa09QDEXej1KEosgFfTS51LzRgOQ5tl3nFdSPmRrCKakQA+T+X3R/+BlMuWVabAdLd+8quG0UVhpcUAwiN8YaXqjFAUnt8Z0SmUaxituVQRk3PWUEVvVPg0CwV9qVA+pROuKUNW4Gm1ppZmpbpZq2iU+OzlQO7sMgH3yIiUgiUjXvkNQAsPN6o6v4kxIvJcrvBfJ+ZoavvTqRSjDq+6gbcG62KEtBpTOFAw6JBzLjXJcv3+N76/byHDV3BpSITFG0mtrZRjVTRF29ITRn0vPeziRczEkkyMsGNZlsh7xJ/i/NGjFBEK1DWFkb9bNNPopXxFfcLxeyUXLT0DHNOMON6aJPm096KJJs1ZtkUBxniCUdwp4rVqG1JiSn+5bLJL1CSxpaWpyzRQxtSjLQKIANt9adzFf/Yax1u/GbcsQyQxr/o6aQ8GEeKGJ0mlTNlJ7ppLL7yT2DtjlyyEP18+T/fZ9KZM9lDsXA377wccnPRfg7pY5F+LUabG8vbytRCozLTZsp9t4GAMIegyjtqgcZX2nGueTtNyOicEBbbP6AIFIG4bUfny4gNJ34IyheXqZCQsIizRDsDbh3TCmVOWmaTbXUiItju41h5kbMWBxfdRKyIYo4+4ZSeAkY0ePbTshx+gfTJBcBNpWc+PTabo4UmuRkOQLz02WddgT6zOd7OPd4meAX3yT1k6g=
    username: AgAe556CE+ERE9i1Qj5wsBDvMmxVPZnoYqN5u/ogSKQvf6/wSGd2UlTD51aCmdcNtpzAWtBlcsAsDCchEQPxCjsm+mPuCTHvVpL1oforqTjRE8tLGhBx62KCfaHsLlgeTGkMuKni2joYodSjlX3LG3zEdd8pcPofeSsBxKpgPivceS2io4ZiIyxyA+ezfWk1TQ7ayVXR2+xiWp/kOaoUvJQMQ9OmdD15y/cTBfSy2A4hJwf/goFKyWP3nzcTHwS85+Oayb16WrH3PMur/UhqF7FtPeJJuz0IRo1AQwVyjGiyYKLs12F76R8EjT/JtJmug4wYOcv1VbjhETECioV9oh2WbD1wuVUazWKMmlNiLh8hACHC9XKJ0piMwSA+phulAeFnLGOKdkGCw1CZo+fKp/UjiJQaROS25zJiy2CF5qtZh635l5mWr9Ddltz82knpL7bC7WuAmsIQmHqGbQwZtwIj7trP2ORiYsem1TSMdh2J2GtffAwEfIBmiWwKGwn88+TGxarr4uwg+67wzEbZqGc7QJ/2UmXD8zB43glhQ+bpvq0+hBho1AqM6DEcSQHSu4EVsEVISMrGCsx3EJ8i3ogoLqj9xVdedXxsr/19/UDYTUnHTLmuj7DAA2h4WD9qvaZ6rJ4xMecukCus8lb9koDrWKykyd8+yiF/6R55faN6Jgp7ul8hKuxeYjHXM3QXECrE3rNWOZFGcw==
  template:
    metadata:
      name: db-credentials
      namespace: prod
