---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgATnRapQCNljoZ+88oThjKoK60aO4lJTr04qMYELfFJW4tOz5xSvix3TmtXZlItU5fWJ+QnqPKGzOVpPzs+WpwNN3Jua3VF/w+DOuGgUM6+GlLkCgYX/apaeMjcSEjNDhWsAd46xyKNOqjMBm5D6MSCP/kk3RNHRpIafNZRDNExReg2UvybJ1SZGeWH5F8d3M0pHPxJamPOzrpghBrtm4YemVyMD4nj1v6kqabygcXdIA9L6B1XoUAh069jb0aFbQj4Mm7/ekla2IvwZKuTXoMQQPRI2e0W74zmalmKz7T316EdhqJQcIg+LhTZp7XZAkGQBCj043+WlHiLRv7GaJepTlaWi/wTDIPDszCBtGDQqKhwKISsHjYVNq8fQCEggZkancC6dLJdXhF+Wo4sNRysRG8okCZDbr3tZI2rLqW2BeRE4RPYVre45sq4V1ahv7Rap1oe6xxgkolWRftQtnXMwFqlSMmSbTCIsaPAOtWD6CJknhYaNJIVh26Yo4D099NZpxxDIce/23UyOgqJHw4b4nxwzqUbmArdYLf34NYbgBa9LBnFzubozhwrFJTLoPDOSRWcdYyr7UKETljoUBBTLP8UI50wdpPcYbeZEfbXLleDbDzDOu6NMyR4kF7I76WHM1zwg2BHnMijZqQo6ZK2MKAK2kNSWoC1rQOZACRmlYXg21ejHMIIoPwBVnRnSIYvPx14pQZWKuz3fQ==
    username: AgBmlNWRpC4Vi2LOmn/+F+/uVoA/9qkoU3LPOi3VogSV2E2FtwBVBM86gP3nXxykJnXEIUEHo3GPf/wiAJTWL0gFcnnjGarXNCAssVCKoUJ8HuOK+KH5BQs/LkwawOu5aLSQ5Os9MAQyPd8SIAF+j+2MoYnu9AWiQXc1q2Q+g/Hq50WMZESO+OT2JvlF1mhC7n07uq1HhWjY8WfxUQOd5FW/hIAAWt93wA2q00xCvAksWSNdGSMmzHvllWvx+XT69b0eZarnJL83VKYJ3ZMWRQpA+LWmm5uvc9BUJRePDqO7CdfSPhu4bpck75H4zGkpHaLzcFW1AxW7Y/ogtRirmrZj9emkK46UW6NTX2gqWQy2LL0E7OVjU1wzWWewaBb3FOAdt3e7rjZlQmJczWgKrMzkivkTGDcPFAITSYSHR2YaJs2PaeTyQyyqvWWzx4fQEdXO8YAsnODMsaMOFNE7VnVh+LqL8ECm9df0cMi61IWxBtseqjCFrseTrH18sCwDVdcgXVRl4pw/mvHjy3kD8RJTXK7cQwQ0zMSwy//bOTckSCswSqkbiipEQlfQ8JdN720SmSGnn70Re9KYwtqUxwHAFGUnwUNhuyMvLSMIbadO4+86HPZHX0Ek343et0hFxEd+Zf1BXmzmN/Fs95TvvzPnyOaMs0ejIpCtzR+FCmMubQQNQ8yluFYu0KPx9vzQpdKbi7bPKbm6
  template:
    metadata:
      name: db-credentials
      namespace: dev
