---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgAqqrDZ/PoyoQ56A+6L2lRRrnHgWj1Brf1VzVCd3jNtVjPcxzX9g3X+HX0qs545T1zL8RNHEqs/vQGUjADvtOFXuajWVN55GROCbe0GgOGaeRAzZXq1LrL9WVJSTNucJAnedX8w5PTlt/a3sDlwu0TD2nNTmaqcHj7aWP7z7SmM5UFAAZXYUOmYwyFmIuNLrSMj2IivlP/visM8wO/AdVv5AUasVGeTpz6pZRGznTfP03n9Y0xkelle/gtuTOHsC7ISLxijG+T/1Y9eFM4I3lif0OUWKExkohm4PePs/Q3XvBeXwdHBNxdep+p0JnE3LR+kzTgUkFSgcvQZ1dm0oMXxNn7Qj6FpmhDAqj3tLzcE+R2mmk982p1R8re+se2WiPR45+FJTL2maMTTIypiBLfjcffGlUNmbVWAUO+0h0CEPIJgCI9Pa6uYznqW5lhn+TG315MlkVemJAE43AKAzv+gO6zp3C0QZaD4iTvfJ26GDZa0HnJ7rsqAiud6sjtSM2GFf7IvAFYITEzYyJrORisKfhjnXCd7CWoSOF8mWXce9r75uG21VdDdLmjh5En7GMKG73S08OV/PuswVnbxpyt5eYSQC4lqu0lly/MFRCcA9qOcdPmQ/ZkabvGLZy5a3tfLS6E6zcHgz+gqao0jQSm7eWbfqT4H6bCgEclk2ZDknSiygV6nfm/Ot2oPuoclScygw0A1eyNxsA==
    username: AgBxiso29JUf/aVxtfUTHQMYgy5//itk6Wdo6eeZ1tui9NepDWfuEBY5sE5Li1tFbmKblRYk8yKMuPT86BnyoldUjR61TDMntxwZ48Im9PJlcic3Y2smVHt7x/le2V8I254gE6EMcSB+sQRI7XAprG6hPV8Q+UJlNAqCsr+1bk4dliyVgis+R7h7+TSvJl2iigqqYFzA3nJMTk1M2JlFVPis+OspK2WkspAkcU6OCykLNreA4VgJJyrXq/SbXD/pOZu702Sf3/OIZrlEFeks98g/DakwicoCkWMPefwCQlv6MD41BVh7m8HdAiU/Geyo9XOTKOnIQE3CBEzoHZfcDVZ/ZMGSB/AiMbU2KcumUhwnGE6Pwkts+ITCNLpECyzsd/jUhpl37bRwr+0G09ng08SrqLRTMNyWAxaAuBccQvLMLJiFoKJSi/cGXQ9Utx9iVP/8OlCCx9pM4GEcf5QeDXL9HhTm2xPaKcyEC1mq1F7o5wBTJKbB+xclbyX6Xpxk09EHh0JkC3wahFfXo+/s+e+PMxG+GZ/nQEevsjdb/wqpeVrsDHr16gx/BgpcCInZFFcYYja/lxasvoi0JhrrNF71iNMcedYcrvcM3fY6JpXBpiatee4CcLI7XGZulg48cWIsw1ETDhlPAz+Anc8pK5C1r12xcpmPKII+mK6YKl3/CN+rOCds1dle9PyBTGJ9+I+LpffevRVbmw==
  template:
    metadata:
      name: db-credentials
      namespace: dev
    type: Opaque
