apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-pt-dev
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/DSebs/prueba_argo
    targetRevision: main
    path: apps/podinfo/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
