apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DSebs/prueba_argo
    targetRevision: qa
    path: apps/podinfo/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
